networks:
  vpn-network: # The bridge network we created earlier
    driver: bridge # Tells docker that the network is pre-existing
    name: vpn-network

services:
  ubuntu:
    cap_add:
      - NET_ADMIN
    build:
      context: ./ubuntu
    network_mode: container:l2tp-vpn-client
    ports:
      - 5900:5900
  l2tp-vpn-client:
    image: r0hm1/l2tp-vpn-client:latest
    container_name: l2tp-vpn-client
    hostname: l2tp-vpn-client
    privileged: true
    networks:
      - vpn-network # The bridge network we created earlier
    cap_add:
      - NET_ADMIN
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - VPN_SERVER_IPV4=${VPN_SERVER_IPV4}
      - VPN_PSK=${VPN_PSK}
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - TZ=Europe/Paris
      - LAN=192.168.1.0/24
    restart: unless-stopped
